version: '3'


services:
  web:
    build: .
    command: yarn run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'e_commerce_db' # create a db by default
      MYSQL_PASSWORD: 'password'
      container_name: ecommerce-mysql-app
    restart: on-failure

  migration:
    build: ./
    command: bash -c "yarn db:migrate:seed"
    links:
      - mysql
    depends_on:
      - mysql